/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.newsletter.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.training.newsletter.model.NewsletterArticle;
import com.liferay.training.newsletter.model.NewsletterArticleModel;
import com.liferay.training.newsletter.model.NewsletterArticleSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the NewsletterArticle service. Represents a row in the &quot;TS_NewsletterArticle&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>NewsletterArticleModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NewsletterArticleImpl}.
 * </p>
 *
 * @author Son Truong
 * @see NewsletterArticleImpl
 * @generated
 */
@JSON(strict = true)
public class NewsletterArticleModelImpl
	extends BaseModelImpl<NewsletterArticle> implements NewsletterArticleModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a newsletter article model instance should use the <code>NewsletterArticle</code> interface instead.
	 */
	public static final String TABLE_NAME = "TS_NewsletterArticle";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"newsletterArticleId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"classNameId", Types.BIGINT}, {"classPK", Types.BIGINT},
		{"resourcePrimKey", Types.BIGINT}, {"title", Types.VARCHAR},
		{"author", Types.VARCHAR}, {"status", Types.INTEGER},
		{"order_", Types.INTEGER}, {"content", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("newsletterArticleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("resourcePrimKey", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("author", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("order_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("content", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table TS_NewsletterArticle (uuid_ VARCHAR(75) null,newsletterArticleId LONG not null primary key,companyId LONG,groupId LONG,classNameId LONG,classPK LONG,resourcePrimKey LONG,title VARCHAR(75) null,author VARCHAR(75) null,status INTEGER,order_ INTEGER,content VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table TS_NewsletterArticle";

	public static final String ORDER_BY_JPQL =
		" ORDER BY newsletterArticle.order DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY TS_NewsletterArticle.order_ DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long RESOURCEPRIMKEY_COLUMN_BITMASK = 4L;

	public static final long UUID_COLUMN_BITMASK = 8L;

	public static final long ORDER_COLUMN_BITMASK = 16L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static NewsletterArticle toModel(NewsletterArticleSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		NewsletterArticle model = new NewsletterArticleImpl();

		model.setUuid(soapModel.getUuid());
		model.setNewsletterArticleId(soapModel.getNewsletterArticleId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setClassNameId(soapModel.getClassNameId());
		model.setClassPK(soapModel.getClassPK());
		model.setResourcePrimKey(soapModel.getResourcePrimKey());
		model.setTitle(soapModel.getTitle());
		model.setAuthor(soapModel.getAuthor());
		model.setStatus(soapModel.getStatus());
		model.setOrder(soapModel.getOrder());
		model.setContent(soapModel.getContent());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<NewsletterArticle> toModels(
		NewsletterArticleSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<NewsletterArticle> models = new ArrayList<NewsletterArticle>(
			soapModels.length);

		for (NewsletterArticleSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public NewsletterArticleModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _newsletterArticleId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setNewsletterArticleId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _newsletterArticleId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return NewsletterArticle.class;
	}

	@Override
	public String getModelClassName() {
		return NewsletterArticle.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<NewsletterArticle, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<NewsletterArticle, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NewsletterArticle, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((NewsletterArticle)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<NewsletterArticle, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<NewsletterArticle, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(NewsletterArticle)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<NewsletterArticle, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<NewsletterArticle, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, NewsletterArticle>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			NewsletterArticle.class.getClassLoader(), NewsletterArticle.class,
			ModelWrapper.class);

		try {
			Constructor<NewsletterArticle> constructor =
				(Constructor<NewsletterArticle>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<NewsletterArticle, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<NewsletterArticle, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<NewsletterArticle, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<NewsletterArticle, Object>>();
		Map<String, BiConsumer<NewsletterArticle, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<NewsletterArticle, ?>>();

		attributeGetterFunctions.put("uuid", NewsletterArticle::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<NewsletterArticle, String>)NewsletterArticle::setUuid);
		attributeGetterFunctions.put(
			"newsletterArticleId", NewsletterArticle::getNewsletterArticleId);
		attributeSetterBiConsumers.put(
			"newsletterArticleId",
			(BiConsumer<NewsletterArticle, Long>)
				NewsletterArticle::setNewsletterArticleId);
		attributeGetterFunctions.put(
			"companyId", NewsletterArticle::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<NewsletterArticle, Long>)
				NewsletterArticle::setCompanyId);
		attributeGetterFunctions.put("groupId", NewsletterArticle::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<NewsletterArticle, Long>)NewsletterArticle::setGroupId);
		attributeGetterFunctions.put(
			"classNameId", NewsletterArticle::getClassNameId);
		attributeSetterBiConsumers.put(
			"classNameId",
			(BiConsumer<NewsletterArticle, Long>)
				NewsletterArticle::setClassNameId);
		attributeGetterFunctions.put("classPK", NewsletterArticle::getClassPK);
		attributeSetterBiConsumers.put(
			"classPK",
			(BiConsumer<NewsletterArticle, Long>)NewsletterArticle::setClassPK);
		attributeGetterFunctions.put(
			"resourcePrimKey", NewsletterArticle::getResourcePrimKey);
		attributeSetterBiConsumers.put(
			"resourcePrimKey",
			(BiConsumer<NewsletterArticle, Long>)
				NewsletterArticle::setResourcePrimKey);
		attributeGetterFunctions.put("title", NewsletterArticle::getTitle);
		attributeSetterBiConsumers.put(
			"title",
			(BiConsumer<NewsletterArticle, String>)NewsletterArticle::setTitle);
		attributeGetterFunctions.put("author", NewsletterArticle::getAuthor);
		attributeSetterBiConsumers.put(
			"author",
			(BiConsumer<NewsletterArticle, String>)
				NewsletterArticle::setAuthor);
		attributeGetterFunctions.put("status", NewsletterArticle::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<NewsletterArticle, Integer>)
				NewsletterArticle::setStatus);
		attributeGetterFunctions.put("order", NewsletterArticle::getOrder);
		attributeSetterBiConsumers.put(
			"order",
			(BiConsumer<NewsletterArticle, Integer>)
				NewsletterArticle::setOrder);
		attributeGetterFunctions.put("content", NewsletterArticle::getContent);
		attributeSetterBiConsumers.put(
			"content",
			(BiConsumer<NewsletterArticle, String>)
				NewsletterArticle::setContent);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getNewsletterArticleId() {
		return _newsletterArticleId;
	}

	@Override
	public void setNewsletterArticleId(long newsletterArticleId) {
		_newsletterArticleId = newsletterArticleId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@JSON
	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		_classNameId = classNameId;
	}

	@JSON
	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		_classPK = classPK;
	}

	@JSON
	@Override
	public long getResourcePrimKey() {
		return _resourcePrimKey;
	}

	@Override
	public void setResourcePrimKey(long resourcePrimKey) {
		_columnBitmask |= RESOURCEPRIMKEY_COLUMN_BITMASK;

		if (!_setOriginalResourcePrimKey) {
			_setOriginalResourcePrimKey = true;

			_originalResourcePrimKey = _resourcePrimKey;
		}

		_resourcePrimKey = resourcePrimKey;
	}

	@Override
	public boolean isResourceMain() {
		return true;
	}

	public long getOriginalResourcePrimKey() {
		return _originalResourcePrimKey;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_title = title;
	}

	@JSON
	@Override
	public String getAuthor() {
		if (_author == null) {
			return "";
		}
		else {
			return _author;
		}
	}

	@Override
	public void setAuthor(String author) {
		_author = author;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@JSON
	@Override
	public int getOrder() {
		return _order;
	}

	@Override
	public void setOrder(int order) {
		_order = order;
	}

	@JSON
	@Override
	public String getContent() {
		if (_content == null) {
			return "";
		}
		else {
			return _content;
		}
	}

	@Override
	public void setContent(String content) {
		_content = content;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), NewsletterArticle.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public NewsletterArticle toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, NewsletterArticle>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		NewsletterArticleImpl newsletterArticleImpl =
			new NewsletterArticleImpl();

		newsletterArticleImpl.setUuid(getUuid());
		newsletterArticleImpl.setNewsletterArticleId(getNewsletterArticleId());
		newsletterArticleImpl.setCompanyId(getCompanyId());
		newsletterArticleImpl.setGroupId(getGroupId());
		newsletterArticleImpl.setClassNameId(getClassNameId());
		newsletterArticleImpl.setClassPK(getClassPK());
		newsletterArticleImpl.setResourcePrimKey(getResourcePrimKey());
		newsletterArticleImpl.setTitle(getTitle());
		newsletterArticleImpl.setAuthor(getAuthor());
		newsletterArticleImpl.setStatus(getStatus());
		newsletterArticleImpl.setOrder(getOrder());
		newsletterArticleImpl.setContent(getContent());

		newsletterArticleImpl.resetOriginalValues();

		return newsletterArticleImpl;
	}

	@Override
	public int compareTo(NewsletterArticle newsletterArticle) {
		int value = 0;

		if (getOrder() < newsletterArticle.getOrder()) {
			value = -1;
		}
		else if (getOrder() > newsletterArticle.getOrder()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof NewsletterArticle)) {
			return false;
		}

		NewsletterArticle newsletterArticle = (NewsletterArticle)object;

		long primaryKey = newsletterArticle.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalResourcePrimKey = _resourcePrimKey;

		_setOriginalResourcePrimKey = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<NewsletterArticle> toCacheModel() {
		NewsletterArticleCacheModel newsletterArticleCacheModel =
			new NewsletterArticleCacheModel();

		newsletterArticleCacheModel.uuid = getUuid();

		String uuid = newsletterArticleCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			newsletterArticleCacheModel.uuid = null;
		}

		newsletterArticleCacheModel.newsletterArticleId =
			getNewsletterArticleId();

		newsletterArticleCacheModel.companyId = getCompanyId();

		newsletterArticleCacheModel.groupId = getGroupId();

		newsletterArticleCacheModel.classNameId = getClassNameId();

		newsletterArticleCacheModel.classPK = getClassPK();

		newsletterArticleCacheModel.resourcePrimKey = getResourcePrimKey();

		newsletterArticleCacheModel.title = getTitle();

		String title = newsletterArticleCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			newsletterArticleCacheModel.title = null;
		}

		newsletterArticleCacheModel.author = getAuthor();

		String author = newsletterArticleCacheModel.author;

		if ((author != null) && (author.length() == 0)) {
			newsletterArticleCacheModel.author = null;
		}

		newsletterArticleCacheModel.status = getStatus();

		newsletterArticleCacheModel.order = getOrder();

		newsletterArticleCacheModel.content = getContent();

		String content = newsletterArticleCacheModel.content;

		if ((content != null) && (content.length() == 0)) {
			newsletterArticleCacheModel.content = null;
		}

		return newsletterArticleCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<NewsletterArticle, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<NewsletterArticle, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NewsletterArticle, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((NewsletterArticle)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<NewsletterArticle, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<NewsletterArticle, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NewsletterArticle, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((NewsletterArticle)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, NewsletterArticle>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _newsletterArticleId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _classNameId;
	private long _classPK;
	private long _resourcePrimKey;
	private long _originalResourcePrimKey;
	private boolean _setOriginalResourcePrimKey;
	private String _title;
	private String _author;
	private int _status;
	private int _order;
	private String _content;
	private long _columnBitmask;
	private NewsletterArticle _escapedModel;

}