/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.newsletter.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.training.newsletter.model.NewsletterIssue;
import com.liferay.training.newsletter.service.NewsletterIssueLocalService;
import com.liferay.training.newsletter.service.persistence.NewsletterArticlePersistence;
import com.liferay.training.newsletter.service.persistence.NewsletterIssuePersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the newsletter issue local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.training.newsletter.service.impl.NewsletterIssueLocalServiceImpl}.
 * </p>
 *
 * @author Son Truong
 * @see com.liferay.training.newsletter.service.impl.NewsletterIssueLocalServiceImpl
 * @generated
 */
public abstract class NewsletterIssueLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   NewsletterIssueLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>NewsletterIssueLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.training.newsletter.service.NewsletterIssueLocalServiceUtil</code>.
	 */

	/**
	 * Adds the newsletter issue to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect NewsletterIssueLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param newsletterIssue the newsletter issue
	 * @return the newsletter issue that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public NewsletterIssue addNewsletterIssue(NewsletterIssue newsletterIssue) {
		newsletterIssue.setNew(true);

		return newsletterIssuePersistence.update(newsletterIssue);
	}

	/**
	 * Creates a new newsletter issue with the primary key. Does not add the newsletter issue to the database.
	 *
	 * @param newsletterIssueId the primary key for the new newsletter issue
	 * @return the new newsletter issue
	 */
	@Override
	@Transactional(enabled = false)
	public NewsletterIssue createNewsletterIssue(long newsletterIssueId) {
		return newsletterIssuePersistence.create(newsletterIssueId);
	}

	/**
	 * Deletes the newsletter issue with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect NewsletterIssueLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param newsletterIssueId the primary key of the newsletter issue
	 * @return the newsletter issue that was removed
	 * @throws PortalException if a newsletter issue with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public NewsletterIssue deleteNewsletterIssue(long newsletterIssueId)
		throws PortalException {

		return newsletterIssuePersistence.remove(newsletterIssueId);
	}

	/**
	 * Deletes the newsletter issue from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect NewsletterIssueLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param newsletterIssue the newsletter issue
	 * @return the newsletter issue that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public NewsletterIssue deleteNewsletterIssue(
		NewsletterIssue newsletterIssue) {

		return newsletterIssuePersistence.remove(newsletterIssue);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			NewsletterIssue.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return newsletterIssuePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.training.newsletter.model.impl.NewsletterIssueModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return newsletterIssuePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.training.newsletter.model.impl.NewsletterIssueModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return newsletterIssuePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return newsletterIssuePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return newsletterIssuePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public NewsletterIssue fetchNewsletterIssue(long newsletterIssueId) {
		return newsletterIssuePersistence.fetchByPrimaryKey(newsletterIssueId);
	}

	/**
	 * Returns the newsletter issue matching the UUID and group.
	 *
	 * @param uuid the newsletter issue's UUID
	 * @param groupId the primary key of the group
	 * @return the matching newsletter issue, or <code>null</code> if a matching newsletter issue could not be found
	 */
	@Override
	public NewsletterIssue fetchNewsletterIssueByUuidAndGroupId(
		String uuid, long groupId) {

		return newsletterIssuePersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the newsletter issue with the primary key.
	 *
	 * @param newsletterIssueId the primary key of the newsletter issue
	 * @return the newsletter issue
	 * @throws PortalException if a newsletter issue with the primary key could not be found
	 */
	@Override
	public NewsletterIssue getNewsletterIssue(long newsletterIssueId)
		throws PortalException {

		return newsletterIssuePersistence.findByPrimaryKey(newsletterIssueId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(newsletterIssueLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(NewsletterIssue.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("newsletterIssueId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			newsletterIssueLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(NewsletterIssue.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"newsletterIssueId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(newsletterIssueLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(NewsletterIssue.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("newsletterIssueId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return newsletterIssueLocalService.deleteNewsletterIssue(
			(NewsletterIssue)persistedModel);
	}

	public BasePersistence<NewsletterIssue> getBasePersistence() {
		return newsletterIssuePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return newsletterIssuePersistence.findByPrimaryKey(primaryKeyObj);
	}

	@Override
	public List<? extends PersistedModel> getPersistedModel(
			long resourcePrimKey)
		throws PortalException {

		return newsletterIssuePersistence.findByResourcePrimKey(
			resourcePrimKey);
	}

	/**
	 * Returns all the newsletter issues matching the UUID and company.
	 *
	 * @param uuid the UUID of the newsletter issues
	 * @param companyId the primary key of the company
	 * @return the matching newsletter issues, or an empty list if no matches were found
	 */
	@Override
	public List<NewsletterIssue> getNewsletterIssuesByUuidAndCompanyId(
		String uuid, long companyId) {

		return newsletterIssuePersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of newsletter issues matching the UUID and company.
	 *
	 * @param uuid the UUID of the newsletter issues
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of newsletter issues
	 * @param end the upper bound of the range of newsletter issues (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching newsletter issues, or an empty list if no matches were found
	 */
	@Override
	public List<NewsletterIssue> getNewsletterIssuesByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<NewsletterIssue> orderByComparator) {

		return newsletterIssuePersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the newsletter issue matching the UUID and group.
	 *
	 * @param uuid the newsletter issue's UUID
	 * @param groupId the primary key of the group
	 * @return the matching newsletter issue
	 * @throws PortalException if a matching newsletter issue could not be found
	 */
	@Override
	public NewsletterIssue getNewsletterIssueByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return newsletterIssuePersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the newsletter issues.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.training.newsletter.model.impl.NewsletterIssueModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of newsletter issues
	 * @param end the upper bound of the range of newsletter issues (not inclusive)
	 * @return the range of newsletter issues
	 */
	@Override
	public List<NewsletterIssue> getNewsletterIssues(int start, int end) {
		return newsletterIssuePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of newsletter issues.
	 *
	 * @return the number of newsletter issues
	 */
	@Override
	public int getNewsletterIssuesCount() {
		return newsletterIssuePersistence.countAll();
	}

	/**
	 * Updates the newsletter issue in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect NewsletterIssueLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param newsletterIssue the newsletter issue
	 * @return the newsletter issue that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public NewsletterIssue updateNewsletterIssue(
		NewsletterIssue newsletterIssue) {

		return newsletterIssuePersistence.update(newsletterIssue);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			NewsletterIssueLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		newsletterIssueLocalService = (NewsletterIssueLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return NewsletterIssueLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return NewsletterIssue.class;
	}

	protected String getModelClassName() {
		return NewsletterIssue.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = newsletterIssuePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected NewsletterArticlePersistence newsletterArticlePersistence;

	protected NewsletterIssueLocalService newsletterIssueLocalService;

	@Reference
	protected NewsletterIssuePersistence newsletterIssuePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetEntryLocalService
		assetEntryLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetTagLocalService
		assetTagLocalService;

}