/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.amf.registration.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserCustom service. Represents a row in the &quot;AmfRegistration_UserCustom&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.training.amf.registration.model.impl.UserCustomModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.training.amf.registration.model.impl.UserCustomImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserCustom
 * @generated
 */
@ProviderType
public interface UserCustomModel extends BaseModel<UserCustom> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user custom model instance should use the {@link UserCustom} interface instead.
	 */

	/**
	 * Returns the primary key of this user custom.
	 *
	 * @return the primary key of this user custom
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user custom.
	 *
	 * @param primaryKey the primary key of this user custom
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user custom ID of this user custom.
	 *
	 * @return the user custom ID of this user custom
	 */
	public long getUserCustomId();

	/**
	 * Sets the user custom ID of this user custom.
	 *
	 * @param userCustomId the user custom ID of this user custom
	 */
	public void setUserCustomId(long userCustomId);

	/**
	 * Returns the home phone of this user custom.
	 *
	 * @return the home phone of this user custom
	 */
	@AutoEscape
	public String getHomePhone();

	/**
	 * Sets the home phone of this user custom.
	 *
	 * @param homePhone the home phone of this user custom
	 */
	public void setHomePhone(String homePhone);

	/**
	 * Returns the mobile phone of this user custom.
	 *
	 * @return the mobile phone of this user custom
	 */
	@AutoEscape
	public String getMobilePhone();

	/**
	 * Sets the mobile phone of this user custom.
	 *
	 * @param mobilePhone the mobile phone of this user custom
	 */
	public void setMobilePhone(String mobilePhone);

	/**
	 * Returns the user ID of this user custom.
	 *
	 * @return the user ID of this user custom
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user custom.
	 *
	 * @param userId the user ID of this user custom
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user custom.
	 *
	 * @return the user uuid of this user custom
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user custom.
	 *
	 * @param userUuid the user uuid of this user custom
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the address of this user custom.
	 *
	 * @return the address of this user custom
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this user custom.
	 *
	 * @param address the address of this user custom
	 */
	public void setAddress(String address);

	/**
	 * Returns the address2 of this user custom.
	 *
	 * @return the address2 of this user custom
	 */
	@AutoEscape
	public String getAddress2();

	/**
	 * Sets the address2 of this user custom.
	 *
	 * @param address2 the address2 of this user custom
	 */
	public void setAddress2(String address2);

	/**
	 * Returns the city of this user custom.
	 *
	 * @return the city of this user custom
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this user custom.
	 *
	 * @param city the city of this user custom
	 */
	public void setCity(String city);

	/**
	 * Returns the state of this user custom.
	 *
	 * @return the state of this user custom
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this user custom.
	 *
	 * @param state the state of this user custom
	 */
	public void setState(String state);

	/**
	 * Returns the zip of this user custom.
	 *
	 * @return the zip of this user custom
	 */
	@AutoEscape
	public String getZip();

	/**
	 * Sets the zip of this user custom.
	 *
	 * @param zip the zip of this user custom
	 */
	public void setZip(String zip);

	/**
	 * Returns the security question of this user custom.
	 *
	 * @return the security question of this user custom
	 */
	@AutoEscape
	public String getSecurityQuestion();

	/**
	 * Sets the security question of this user custom.
	 *
	 * @param securityQuestion the security question of this user custom
	 */
	public void setSecurityQuestion(String securityQuestion);

	/**
	 * Returns the security answer of this user custom.
	 *
	 * @return the security answer of this user custom
	 */
	@AutoEscape
	public String getSecurityAnswer();

	/**
	 * Sets the security answer of this user custom.
	 *
	 * @param securityAnswer the security answer of this user custom
	 */
	public void setSecurityAnswer(String securityAnswer);

	/**
	 * Returns the accepted tou of this user custom.
	 *
	 * @return the accepted tou of this user custom
	 */
	public boolean getAcceptedTou();

	/**
	 * Returns <code>true</code> if this user custom is accepted tou.
	 *
	 * @return <code>true</code> if this user custom is accepted tou; <code>false</code> otherwise
	 */
	public boolean isAcceptedTou();

	/**
	 * Sets whether this user custom is accepted tou.
	 *
	 * @param acceptedTou the accepted tou of this user custom
	 */
	public void setAcceptedTou(boolean acceptedTou);

}