/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.newsletter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ResourcedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the NewsletterIssue service. Represents a row in the &quot;TS_NewsletterIssue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.training.newsletter.model.impl.NewsletterIssueModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.training.newsletter.model.impl.NewsletterIssueImpl</code>.
 * </p>
 *
 * @author Son Truong
 * @see NewsletterIssue
 * @generated
 */
@ProviderType
public interface NewsletterIssueModel
	extends BaseModel<NewsletterIssue>, ResourcedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a newsletter issue model instance should use the {@link NewsletterIssue} interface instead.
	 */

	/**
	 * Returns the primary key of this newsletter issue.
	 *
	 * @return the primary key of this newsletter issue
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this newsletter issue.
	 *
	 * @param primaryKey the primary key of this newsletter issue
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this newsletter issue.
	 *
	 * @return the uuid of this newsletter issue
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this newsletter issue.
	 *
	 * @param uuid the uuid of this newsletter issue
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the newsletter issue ID of this newsletter issue.
	 *
	 * @return the newsletter issue ID of this newsletter issue
	 */
	public long getNewsletterIssueId();

	/**
	 * Sets the newsletter issue ID of this newsletter issue.
	 *
	 * @param newsletterIssueId the newsletter issue ID of this newsletter issue
	 */
	public void setNewsletterIssueId(long newsletterIssueId);

	/**
	 * Returns the company ID of this newsletter issue.
	 *
	 * @return the company ID of this newsletter issue
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this newsletter issue.
	 *
	 * @param companyId the company ID of this newsletter issue
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this newsletter issue.
	 *
	 * @return the group ID of this newsletter issue
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this newsletter issue.
	 *
	 * @param groupId the group ID of this newsletter issue
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the issue number of this newsletter issue.
	 *
	 * @return the issue number of this newsletter issue
	 */
	public int getIssueNumber();

	/**
	 * Sets the issue number of this newsletter issue.
	 *
	 * @param issueNumber the issue number of this newsletter issue
	 */
	public void setIssueNumber(int issueNumber);

	/**
	 * Returns the title of this newsletter issue.
	 *
	 * @return the title of this newsletter issue
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this newsletter issue.
	 *
	 * @param title the title of this newsletter issue
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this newsletter issue.
	 *
	 * @return the description of this newsletter issue
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this newsletter issue.
	 *
	 * @param description the description of this newsletter issue
	 */
	public void setDescription(String description);

	/**
	 * Returns the issue date of this newsletter issue.
	 *
	 * @return the issue date of this newsletter issue
	 */
	public Date getIssueDate();

	/**
	 * Sets the issue date of this newsletter issue.
	 *
	 * @param issueDate the issue date of this newsletter issue
	 */
	public void setIssueDate(Date issueDate);

	/**
	 * Returns the status of this newsletter issue.
	 *
	 * @return the status of this newsletter issue
	 */
	public int getStatus();

	/**
	 * Sets the status of this newsletter issue.
	 *
	 * @param status the status of this newsletter issue
	 */
	public void setStatus(int status);

	/**
	 * Returns the resource prim key of this newsletter issue.
	 *
	 * @return the resource prim key of this newsletter issue
	 */
	@Override
	public long getResourcePrimKey();

	/**
	 * Sets the resource prim key of this newsletter issue.
	 *
	 * @param resourcePrimKey the resource prim key of this newsletter issue
	 */
	@Override
	public void setResourcePrimKey(long resourcePrimKey);

	@Override
	public boolean isResourceMain();

}