/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.amf.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.training.amf.model.AmfAuditEvent;
import com.liferay.training.amf.model.AmfAuditEventModel;
import com.liferay.training.amf.model.AmfAuditEventSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AmfAuditEvent service. Represents a row in the &quot;Amf_AmfAuditEvent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AmfAuditEventModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AmfAuditEventImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AmfAuditEventImpl
 * @generated
 */
@JSON(strict = true)
public class AmfAuditEventModelImpl
	extends BaseModelImpl<AmfAuditEvent> implements AmfAuditEventModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a amf audit event model instance should use the <code>AmfAuditEvent</code> interface instead.
	 */
	public static final String TABLE_NAME = "Amf_AmfAuditEvent";

	public static final Object[][] TABLE_COLUMNS = {
		{"amfAuditEventId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"eventType", Types.VARCHAR},
		{"ipAddress", Types.VARCHAR}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("amfAuditEventId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("eventType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ipAddress", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Amf_AmfAuditEvent (amfAuditEventId LONG not null primary key,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,eventType VARCHAR(75) null,ipAddress VARCHAR(75) null,groupId LONG,companyId LONG)";

	public static final String TABLE_SQL_DROP = "drop table Amf_AmfAuditEvent";

	public static final String ORDER_BY_JPQL =
		" ORDER BY amfAuditEvent.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Amf_AmfAuditEvent.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long EVENTTYPE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static AmfAuditEvent toModel(AmfAuditEventSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		AmfAuditEvent model = new AmfAuditEventImpl();

		model.setAmfAuditEventId(soapModel.getAmfAuditEventId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setEventType(soapModel.getEventType());
		model.setIpAddress(soapModel.getIpAddress());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<AmfAuditEvent> toModels(AmfAuditEventSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<AmfAuditEvent> models = new ArrayList<AmfAuditEvent>(
			soapModels.length);

		for (AmfAuditEventSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public AmfAuditEventModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _amfAuditEventId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAmfAuditEventId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _amfAuditEventId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AmfAuditEvent.class;
	}

	@Override
	public String getModelClassName() {
		return AmfAuditEvent.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AmfAuditEvent, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AmfAuditEvent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AmfAuditEvent, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AmfAuditEvent)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AmfAuditEvent, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AmfAuditEvent, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AmfAuditEvent)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AmfAuditEvent, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AmfAuditEvent, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, AmfAuditEvent>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			AmfAuditEvent.class.getClassLoader(), AmfAuditEvent.class,
			ModelWrapper.class);

		try {
			Constructor<AmfAuditEvent> constructor =
				(Constructor<AmfAuditEvent>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<AmfAuditEvent, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<AmfAuditEvent, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<AmfAuditEvent, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<AmfAuditEvent, Object>>();
		Map<String, BiConsumer<AmfAuditEvent, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<AmfAuditEvent, ?>>();

		attributeGetterFunctions.put(
			"amfAuditEventId", AmfAuditEvent::getAmfAuditEventId);
		attributeSetterBiConsumers.put(
			"amfAuditEventId",
			(BiConsumer<AmfAuditEvent, Long>)AmfAuditEvent::setAmfAuditEventId);
		attributeGetterFunctions.put("userId", AmfAuditEvent::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<AmfAuditEvent, Long>)AmfAuditEvent::setUserId);
		attributeGetterFunctions.put("userName", AmfAuditEvent::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<AmfAuditEvent, String>)AmfAuditEvent::setUserName);
		attributeGetterFunctions.put(
			"createDate", AmfAuditEvent::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<AmfAuditEvent, Date>)AmfAuditEvent::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", AmfAuditEvent::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<AmfAuditEvent, Date>)AmfAuditEvent::setModifiedDate);
		attributeGetterFunctions.put("eventType", AmfAuditEvent::getEventType);
		attributeSetterBiConsumers.put(
			"eventType",
			(BiConsumer<AmfAuditEvent, String>)AmfAuditEvent::setEventType);
		attributeGetterFunctions.put("ipAddress", AmfAuditEvent::getIpAddress);
		attributeSetterBiConsumers.put(
			"ipAddress",
			(BiConsumer<AmfAuditEvent, String>)AmfAuditEvent::setIpAddress);
		attributeGetterFunctions.put("groupId", AmfAuditEvent::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<AmfAuditEvent, Long>)AmfAuditEvent::setGroupId);
		attributeGetterFunctions.put("companyId", AmfAuditEvent::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<AmfAuditEvent, Long>)AmfAuditEvent::setCompanyId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getAmfAuditEventId() {
		return _amfAuditEventId;
	}

	@Override
	public void setAmfAuditEventId(long amfAuditEventId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_amfAuditEventId = amfAuditEventId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getEventType() {
		if (_eventType == null) {
			return "";
		}
		else {
			return _eventType;
		}
	}

	@Override
	public void setEventType(String eventType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_eventType = eventType;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalEventType() {
		return getColumnOriginalValue("eventType");
	}

	@JSON
	@Override
	public String getIpAddress() {
		if (_ipAddress == null) {
			return "";
		}
		else {
			return _ipAddress;
		}
	}

	@Override
	public void setIpAddress(String ipAddress) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ipAddress = ipAddress;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AmfAuditEvent.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AmfAuditEvent toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AmfAuditEvent>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AmfAuditEventImpl amfAuditEventImpl = new AmfAuditEventImpl();

		amfAuditEventImpl.setAmfAuditEventId(getAmfAuditEventId());
		amfAuditEventImpl.setUserId(getUserId());
		amfAuditEventImpl.setUserName(getUserName());
		amfAuditEventImpl.setCreateDate(getCreateDate());
		amfAuditEventImpl.setModifiedDate(getModifiedDate());
		amfAuditEventImpl.setEventType(getEventType());
		amfAuditEventImpl.setIpAddress(getIpAddress());
		amfAuditEventImpl.setGroupId(getGroupId());
		amfAuditEventImpl.setCompanyId(getCompanyId());

		amfAuditEventImpl.resetOriginalValues();

		return amfAuditEventImpl;
	}

	@Override
	public int compareTo(AmfAuditEvent amfAuditEvent) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), amfAuditEvent.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AmfAuditEvent)) {
			return false;
		}

		AmfAuditEvent amfAuditEvent = (AmfAuditEvent)object;

		long primaryKey = amfAuditEvent.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AmfAuditEvent> toCacheModel() {
		AmfAuditEventCacheModel amfAuditEventCacheModel =
			new AmfAuditEventCacheModel();

		amfAuditEventCacheModel.amfAuditEventId = getAmfAuditEventId();

		amfAuditEventCacheModel.userId = getUserId();

		amfAuditEventCacheModel.userName = getUserName();

		String userName = amfAuditEventCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			amfAuditEventCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			amfAuditEventCacheModel.createDate = createDate.getTime();
		}
		else {
			amfAuditEventCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			amfAuditEventCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			amfAuditEventCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		amfAuditEventCacheModel.eventType = getEventType();

		String eventType = amfAuditEventCacheModel.eventType;

		if ((eventType != null) && (eventType.length() == 0)) {
			amfAuditEventCacheModel.eventType = null;
		}

		amfAuditEventCacheModel.ipAddress = getIpAddress();

		String ipAddress = amfAuditEventCacheModel.ipAddress;

		if ((ipAddress != null) && (ipAddress.length() == 0)) {
			amfAuditEventCacheModel.ipAddress = null;
		}

		amfAuditEventCacheModel.groupId = getGroupId();

		amfAuditEventCacheModel.companyId = getCompanyId();

		return amfAuditEventCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AmfAuditEvent, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AmfAuditEvent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AmfAuditEvent, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((AmfAuditEvent)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<AmfAuditEvent, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<AmfAuditEvent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AmfAuditEvent, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((AmfAuditEvent)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AmfAuditEvent>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _amfAuditEventId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _eventType;
	private String _ipAddress;
	private long _groupId;
	private long _companyId;

	public <T> T getColumnValue(String columnName) {
		Function<AmfAuditEvent, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AmfAuditEvent)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("amfAuditEventId", _amfAuditEventId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("eventType", _eventType);
		_columnOriginalValues.put("ipAddress", _ipAddress);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("amfAuditEventId", 1L);

		columnBitmasks.put("userId", 2L);

		columnBitmasks.put("userName", 4L);

		columnBitmasks.put("createDate", 8L);

		columnBitmasks.put("modifiedDate", 16L);

		columnBitmasks.put("eventType", 32L);

		columnBitmasks.put("ipAddress", 64L);

		columnBitmasks.put("groupId", 128L);

		columnBitmasks.put("companyId", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AmfAuditEvent _escapedModel;

}