/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.amf.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.training.amf.model.Member;
import com.liferay.training.amf.model.MemberModel;
import com.liferay.training.amf.model.MemberSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Member service. Represents a row in the &quot;Amf_Member&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>MemberModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MemberImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MemberImpl
 * @generated
 */
@JSON(strict = true)
public class MemberModelImpl
	extends BaseModelImpl<Member> implements MemberModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a member model instance should use the <code>Member</code> interface instead.
	 */
	public static final String TABLE_NAME = "Amf_Member";

	public static final Object[][] TABLE_COLUMNS = {
		{"memberId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"firstName", Types.VARCHAR},
		{"lastName", Types.VARCHAR}, {"emailAddress", Types.VARCHAR},
		{"male", Types.BOOLEAN}, {"monthOfBirth", Types.INTEGER},
		{"dayOfBirth", Types.INTEGER}, {"yearOfBirth", Types.INTEGER},
		{"password_", Types.VARCHAR}, {"homePhone", Types.VARCHAR},
		{"mobilePhone", Types.VARCHAR}, {"address1", Types.VARCHAR},
		{"address2", Types.VARCHAR}, {"city", Types.VARCHAR},
		{"state_", Types.VARCHAR}, {"zipCode", Types.VARCHAR},
		{"securityQuestion", Types.VARCHAR}, {"answer", Types.VARCHAR},
		{"termOfUse", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("memberId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("firstName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("emailAddress", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("male", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("monthOfBirth", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("dayOfBirth", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("yearOfBirth", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("password_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("homePhone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("mobilePhone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("address1", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("address2", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("city", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("state_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("zipCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("securityQuestion", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("answer", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("termOfUse", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Amf_Member (memberId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,firstName VARCHAR(75) null,lastName VARCHAR(75) null,emailAddress VARCHAR(75) null,male BOOLEAN,monthOfBirth INTEGER,dayOfBirth INTEGER,yearOfBirth INTEGER,password_ VARCHAR(75) null,homePhone VARCHAR(75) null,mobilePhone VARCHAR(75) null,address1 VARCHAR(75) null,address2 VARCHAR(75) null,city VARCHAR(75) null,state_ VARCHAR(75) null,zipCode VARCHAR(75) null,securityQuestion VARCHAR(75) null,answer VARCHAR(75) null,termOfUse BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table Amf_Member";

	public static final String ORDER_BY_JPQL = " ORDER BY member_.userName ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Amf_Member.userName ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long USERNAME_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static Member toModel(MemberSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Member model = new MemberImpl();

		model.setMemberId(soapModel.getMemberId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setFirstName(soapModel.getFirstName());
		model.setLastName(soapModel.getLastName());
		model.setEmailAddress(soapModel.getEmailAddress());
		model.setMale(soapModel.isMale());
		model.setMonthOfBirth(soapModel.getMonthOfBirth());
		model.setDayOfBirth(soapModel.getDayOfBirth());
		model.setYearOfBirth(soapModel.getYearOfBirth());
		model.setPassword(soapModel.getPassword());
		model.setHomePhone(soapModel.getHomePhone());
		model.setMobilePhone(soapModel.getMobilePhone());
		model.setAddress1(soapModel.getAddress1());
		model.setAddress2(soapModel.getAddress2());
		model.setCity(soapModel.getCity());
		model.setState(soapModel.getState());
		model.setZipCode(soapModel.getZipCode());
		model.setSecurityQuestion(soapModel.getSecurityQuestion());
		model.setAnswer(soapModel.getAnswer());
		model.setTermOfUse(soapModel.isTermOfUse());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<Member> toModels(MemberSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Member> models = new ArrayList<Member>(soapModels.length);

		for (MemberSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public MemberModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _memberId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMemberId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _memberId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Member.class;
	}

	@Override
	public String getModelClassName() {
		return Member.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Member, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Member, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Member, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Member)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Member, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Member, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Member)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Member, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Member, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Member>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Member.class.getClassLoader(), Member.class, ModelWrapper.class);

		try {
			Constructor<Member> constructor =
				(Constructor<Member>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Member, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Member, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Member, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Member, Object>>();
		Map<String, BiConsumer<Member, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Member, ?>>();

		attributeGetterFunctions.put("memberId", Member::getMemberId);
		attributeSetterBiConsumers.put(
			"memberId", (BiConsumer<Member, Long>)Member::setMemberId);
		attributeGetterFunctions.put("groupId", Member::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Member, Long>)Member::setGroupId);
		attributeGetterFunctions.put("companyId", Member::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Member, Long>)Member::setCompanyId);
		attributeGetterFunctions.put("userId", Member::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Member, Long>)Member::setUserId);
		attributeGetterFunctions.put("userName", Member::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Member, String>)Member::setUserName);
		attributeGetterFunctions.put("createDate", Member::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Member, Date>)Member::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Member::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<Member, Date>)Member::setModifiedDate);
		attributeGetterFunctions.put("firstName", Member::getFirstName);
		attributeSetterBiConsumers.put(
			"firstName", (BiConsumer<Member, String>)Member::setFirstName);
		attributeGetterFunctions.put("lastName", Member::getLastName);
		attributeSetterBiConsumers.put(
			"lastName", (BiConsumer<Member, String>)Member::setLastName);
		attributeGetterFunctions.put("emailAddress", Member::getEmailAddress);
		attributeSetterBiConsumers.put(
			"emailAddress",
			(BiConsumer<Member, String>)Member::setEmailAddress);
		attributeGetterFunctions.put("male", Member::getMale);
		attributeSetterBiConsumers.put(
			"male", (BiConsumer<Member, Boolean>)Member::setMale);
		attributeGetterFunctions.put("monthOfBirth", Member::getMonthOfBirth);
		attributeSetterBiConsumers.put(
			"monthOfBirth",
			(BiConsumer<Member, Integer>)Member::setMonthOfBirth);
		attributeGetterFunctions.put("dayOfBirth", Member::getDayOfBirth);
		attributeSetterBiConsumers.put(
			"dayOfBirth", (BiConsumer<Member, Integer>)Member::setDayOfBirth);
		attributeGetterFunctions.put("yearOfBirth", Member::getYearOfBirth);
		attributeSetterBiConsumers.put(
			"yearOfBirth", (BiConsumer<Member, Integer>)Member::setYearOfBirth);
		attributeGetterFunctions.put("password", Member::getPassword);
		attributeSetterBiConsumers.put(
			"password", (BiConsumer<Member, String>)Member::setPassword);
		attributeGetterFunctions.put("homePhone", Member::getHomePhone);
		attributeSetterBiConsumers.put(
			"homePhone", (BiConsumer<Member, String>)Member::setHomePhone);
		attributeGetterFunctions.put("mobilePhone", Member::getMobilePhone);
		attributeSetterBiConsumers.put(
			"mobilePhone", (BiConsumer<Member, String>)Member::setMobilePhone);
		attributeGetterFunctions.put("address1", Member::getAddress1);
		attributeSetterBiConsumers.put(
			"address1", (BiConsumer<Member, String>)Member::setAddress1);
		attributeGetterFunctions.put("address2", Member::getAddress2);
		attributeSetterBiConsumers.put(
			"address2", (BiConsumer<Member, String>)Member::setAddress2);
		attributeGetterFunctions.put("city", Member::getCity);
		attributeSetterBiConsumers.put(
			"city", (BiConsumer<Member, String>)Member::setCity);
		attributeGetterFunctions.put("state", Member::getState);
		attributeSetterBiConsumers.put(
			"state", (BiConsumer<Member, String>)Member::setState);
		attributeGetterFunctions.put("zipCode", Member::getZipCode);
		attributeSetterBiConsumers.put(
			"zipCode", (BiConsumer<Member, String>)Member::setZipCode);
		attributeGetterFunctions.put(
			"securityQuestion", Member::getSecurityQuestion);
		attributeSetterBiConsumers.put(
			"securityQuestion",
			(BiConsumer<Member, String>)Member::setSecurityQuestion);
		attributeGetterFunctions.put("answer", Member::getAnswer);
		attributeSetterBiConsumers.put(
			"answer", (BiConsumer<Member, String>)Member::setAnswer);
		attributeGetterFunctions.put("termOfUse", Member::getTermOfUse);
		attributeSetterBiConsumers.put(
			"termOfUse", (BiConsumer<Member, Boolean>)Member::setTermOfUse);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMemberId() {
		return _memberId;
	}

	@Override
	public void setMemberId(long memberId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_memberId = memberId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getFirstName() {
		if (_firstName == null) {
			return "";
		}
		else {
			return _firstName;
		}
	}

	@Override
	public void setFirstName(String firstName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_firstName = firstName;
	}

	@JSON
	@Override
	public String getLastName() {
		if (_lastName == null) {
			return "";
		}
		else {
			return _lastName;
		}
	}

	@Override
	public void setLastName(String lastName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastName = lastName;
	}

	@JSON
	@Override
	public String getEmailAddress() {
		if (_emailAddress == null) {
			return "";
		}
		else {
			return _emailAddress;
		}
	}

	@Override
	public void setEmailAddress(String emailAddress) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_emailAddress = emailAddress;
	}

	@JSON
	@Override
	public boolean getMale() {
		return _male;
	}

	@JSON
	@Override
	public boolean isMale() {
		return _male;
	}

	@Override
	public void setMale(boolean male) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_male = male;
	}

	@JSON
	@Override
	public int getMonthOfBirth() {
		return _monthOfBirth;
	}

	@Override
	public void setMonthOfBirth(int monthOfBirth) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_monthOfBirth = monthOfBirth;
	}

	@JSON
	@Override
	public int getDayOfBirth() {
		return _dayOfBirth;
	}

	@Override
	public void setDayOfBirth(int dayOfBirth) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dayOfBirth = dayOfBirth;
	}

	@JSON
	@Override
	public int getYearOfBirth() {
		return _yearOfBirth;
	}

	@Override
	public void setYearOfBirth(int yearOfBirth) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_yearOfBirth = yearOfBirth;
	}

	@JSON
	@Override
	public String getPassword() {
		if (_password == null) {
			return "";
		}
		else {
			return _password;
		}
	}

	@Override
	public void setPassword(String password) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_password = password;
	}

	@JSON
	@Override
	public String getHomePhone() {
		if (_homePhone == null) {
			return "";
		}
		else {
			return _homePhone;
		}
	}

	@Override
	public void setHomePhone(String homePhone) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_homePhone = homePhone;
	}

	@JSON
	@Override
	public String getMobilePhone() {
		if (_mobilePhone == null) {
			return "";
		}
		else {
			return _mobilePhone;
		}
	}

	@Override
	public void setMobilePhone(String mobilePhone) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mobilePhone = mobilePhone;
	}

	@JSON
	@Override
	public String getAddress1() {
		if (_address1 == null) {
			return "";
		}
		else {
			return _address1;
		}
	}

	@Override
	public void setAddress1(String address1) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_address1 = address1;
	}

	@JSON
	@Override
	public String getAddress2() {
		if (_address2 == null) {
			return "";
		}
		else {
			return _address2;
		}
	}

	@Override
	public void setAddress2(String address2) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_address2 = address2;
	}

	@JSON
	@Override
	public String getCity() {
		if (_city == null) {
			return "";
		}
		else {
			return _city;
		}
	}

	@Override
	public void setCity(String city) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_city = city;
	}

	@JSON
	@Override
	public String getState() {
		if (_state == null) {
			return "";
		}
		else {
			return _state;
		}
	}

	@Override
	public void setState(String state) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_state = state;
	}

	@JSON
	@Override
	public String getZipCode() {
		if (_zipCode == null) {
			return "";
		}
		else {
			return _zipCode;
		}
	}

	@Override
	public void setZipCode(String zipCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_zipCode = zipCode;
	}

	@JSON
	@Override
	public String getSecurityQuestion() {
		if (_securityQuestion == null) {
			return "";
		}
		else {
			return _securityQuestion;
		}
	}

	@Override
	public void setSecurityQuestion(String securityQuestion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_securityQuestion = securityQuestion;
	}

	@JSON
	@Override
	public String getAnswer() {
		if (_answer == null) {
			return "";
		}
		else {
			return _answer;
		}
	}

	@Override
	public void setAnswer(String answer) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_answer = answer;
	}

	@JSON
	@Override
	public boolean getTermOfUse() {
		return _termOfUse;
	}

	@JSON
	@Override
	public boolean isTermOfUse() {
		return _termOfUse;
	}

	@Override
	public void setTermOfUse(boolean termOfUse) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_termOfUse = termOfUse;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Member.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Member toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Member>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MemberImpl memberImpl = new MemberImpl();

		memberImpl.setMemberId(getMemberId());
		memberImpl.setGroupId(getGroupId());
		memberImpl.setCompanyId(getCompanyId());
		memberImpl.setUserId(getUserId());
		memberImpl.setUserName(getUserName());
		memberImpl.setCreateDate(getCreateDate());
		memberImpl.setModifiedDate(getModifiedDate());
		memberImpl.setFirstName(getFirstName());
		memberImpl.setLastName(getLastName());
		memberImpl.setEmailAddress(getEmailAddress());
		memberImpl.setMale(isMale());
		memberImpl.setMonthOfBirth(getMonthOfBirth());
		memberImpl.setDayOfBirth(getDayOfBirth());
		memberImpl.setYearOfBirth(getYearOfBirth());
		memberImpl.setPassword(getPassword());
		memberImpl.setHomePhone(getHomePhone());
		memberImpl.setMobilePhone(getMobilePhone());
		memberImpl.setAddress1(getAddress1());
		memberImpl.setAddress2(getAddress2());
		memberImpl.setCity(getCity());
		memberImpl.setState(getState());
		memberImpl.setZipCode(getZipCode());
		memberImpl.setSecurityQuestion(getSecurityQuestion());
		memberImpl.setAnswer(getAnswer());
		memberImpl.setTermOfUse(isTermOfUse());

		memberImpl.resetOriginalValues();

		return memberImpl;
	}

	@Override
	public int compareTo(Member member) {
		int value = 0;

		value = getUserName().compareTo(member.getUserName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Member)) {
			return false;
		}

		Member member = (Member)object;

		long primaryKey = member.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Member> toCacheModel() {
		MemberCacheModel memberCacheModel = new MemberCacheModel();

		memberCacheModel.memberId = getMemberId();

		memberCacheModel.groupId = getGroupId();

		memberCacheModel.companyId = getCompanyId();

		memberCacheModel.userId = getUserId();

		memberCacheModel.userName = getUserName();

		String userName = memberCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			memberCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			memberCacheModel.createDate = createDate.getTime();
		}
		else {
			memberCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			memberCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			memberCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		memberCacheModel.firstName = getFirstName();

		String firstName = memberCacheModel.firstName;

		if ((firstName != null) && (firstName.length() == 0)) {
			memberCacheModel.firstName = null;
		}

		memberCacheModel.lastName = getLastName();

		String lastName = memberCacheModel.lastName;

		if ((lastName != null) && (lastName.length() == 0)) {
			memberCacheModel.lastName = null;
		}

		memberCacheModel.emailAddress = getEmailAddress();

		String emailAddress = memberCacheModel.emailAddress;

		if ((emailAddress != null) && (emailAddress.length() == 0)) {
			memberCacheModel.emailAddress = null;
		}

		memberCacheModel.male = isMale();

		memberCacheModel.monthOfBirth = getMonthOfBirth();

		memberCacheModel.dayOfBirth = getDayOfBirth();

		memberCacheModel.yearOfBirth = getYearOfBirth();

		memberCacheModel.password = getPassword();

		String password = memberCacheModel.password;

		if ((password != null) && (password.length() == 0)) {
			memberCacheModel.password = null;
		}

		memberCacheModel.homePhone = getHomePhone();

		String homePhone = memberCacheModel.homePhone;

		if ((homePhone != null) && (homePhone.length() == 0)) {
			memberCacheModel.homePhone = null;
		}

		memberCacheModel.mobilePhone = getMobilePhone();

		String mobilePhone = memberCacheModel.mobilePhone;

		if ((mobilePhone != null) && (mobilePhone.length() == 0)) {
			memberCacheModel.mobilePhone = null;
		}

		memberCacheModel.address1 = getAddress1();

		String address1 = memberCacheModel.address1;

		if ((address1 != null) && (address1.length() == 0)) {
			memberCacheModel.address1 = null;
		}

		memberCacheModel.address2 = getAddress2();

		String address2 = memberCacheModel.address2;

		if ((address2 != null) && (address2.length() == 0)) {
			memberCacheModel.address2 = null;
		}

		memberCacheModel.city = getCity();

		String city = memberCacheModel.city;

		if ((city != null) && (city.length() == 0)) {
			memberCacheModel.city = null;
		}

		memberCacheModel.state = getState();

		String state = memberCacheModel.state;

		if ((state != null) && (state.length() == 0)) {
			memberCacheModel.state = null;
		}

		memberCacheModel.zipCode = getZipCode();

		String zipCode = memberCacheModel.zipCode;

		if ((zipCode != null) && (zipCode.length() == 0)) {
			memberCacheModel.zipCode = null;
		}

		memberCacheModel.securityQuestion = getSecurityQuestion();

		String securityQuestion = memberCacheModel.securityQuestion;

		if ((securityQuestion != null) && (securityQuestion.length() == 0)) {
			memberCacheModel.securityQuestion = null;
		}

		memberCacheModel.answer = getAnswer();

		String answer = memberCacheModel.answer;

		if ((answer != null) && (answer.length() == 0)) {
			memberCacheModel.answer = null;
		}

		memberCacheModel.termOfUse = isTermOfUse();

		return memberCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Member, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Member, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Member, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Member)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Member, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Member, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Member, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Member)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Member>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _memberId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _firstName;
	private String _lastName;
	private String _emailAddress;
	private boolean _male;
	private int _monthOfBirth;
	private int _dayOfBirth;
	private int _yearOfBirth;
	private String _password;
	private String _homePhone;
	private String _mobilePhone;
	private String _address1;
	private String _address2;
	private String _city;
	private String _state;
	private String _zipCode;
	private String _securityQuestion;
	private String _answer;
	private boolean _termOfUse;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Member, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Member)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("memberId", _memberId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("firstName", _firstName);
		_columnOriginalValues.put("lastName", _lastName);
		_columnOriginalValues.put("emailAddress", _emailAddress);
		_columnOriginalValues.put("male", _male);
		_columnOriginalValues.put("monthOfBirth", _monthOfBirth);
		_columnOriginalValues.put("dayOfBirth", _dayOfBirth);
		_columnOriginalValues.put("yearOfBirth", _yearOfBirth);
		_columnOriginalValues.put("password_", _password);
		_columnOriginalValues.put("homePhone", _homePhone);
		_columnOriginalValues.put("mobilePhone", _mobilePhone);
		_columnOriginalValues.put("address1", _address1);
		_columnOriginalValues.put("address2", _address2);
		_columnOriginalValues.put("city", _city);
		_columnOriginalValues.put("state_", _state);
		_columnOriginalValues.put("zipCode", _zipCode);
		_columnOriginalValues.put("securityQuestion", _securityQuestion);
		_columnOriginalValues.put("answer", _answer);
		_columnOriginalValues.put("termOfUse", _termOfUse);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("password_", "password");
		attributeNames.put("state_", "state");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("memberId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("firstName", 128L);

		columnBitmasks.put("lastName", 256L);

		columnBitmasks.put("emailAddress", 512L);

		columnBitmasks.put("male", 1024L);

		columnBitmasks.put("monthOfBirth", 2048L);

		columnBitmasks.put("dayOfBirth", 4096L);

		columnBitmasks.put("yearOfBirth", 8192L);

		columnBitmasks.put("password_", 16384L);

		columnBitmasks.put("homePhone", 32768L);

		columnBitmasks.put("mobilePhone", 65536L);

		columnBitmasks.put("address1", 131072L);

		columnBitmasks.put("address2", 262144L);

		columnBitmasks.put("city", 524288L);

		columnBitmasks.put("state_", 1048576L);

		columnBitmasks.put("zipCode", 2097152L);

		columnBitmasks.put("securityQuestion", 4194304L);

		columnBitmasks.put("answer", 8388608L);

		columnBitmasks.put("termOfUse", 16777216L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Member _escapedModel;

}