/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.amf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AmfAuditEvent service. Represents a row in the &quot;Amf_AmfAuditEvent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.training.amf.model.impl.AmfAuditEventModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.training.amf.model.impl.AmfAuditEventImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AmfAuditEvent
 * @generated
 */
@ProviderType
public interface AmfAuditEventModel
	extends BaseModel<AmfAuditEvent>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a amf audit event model instance should use the {@link AmfAuditEvent} interface instead.
	 */

	/**
	 * Returns the primary key of this amf audit event.
	 *
	 * @return the primary key of this amf audit event
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this amf audit event.
	 *
	 * @param primaryKey the primary key of this amf audit event
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the amf audit event ID of this amf audit event.
	 *
	 * @return the amf audit event ID of this amf audit event
	 */
	public long getAmfAuditEventId();

	/**
	 * Sets the amf audit event ID of this amf audit event.
	 *
	 * @param amfAuditEventId the amf audit event ID of this amf audit event
	 */
	public void setAmfAuditEventId(long amfAuditEventId);

	/**
	 * Returns the user ID of this amf audit event.
	 *
	 * @return the user ID of this amf audit event
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this amf audit event.
	 *
	 * @param userId the user ID of this amf audit event
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this amf audit event.
	 *
	 * @return the user uuid of this amf audit event
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this amf audit event.
	 *
	 * @param userUuid the user uuid of this amf audit event
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this amf audit event.
	 *
	 * @return the user name of this amf audit event
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this amf audit event.
	 *
	 * @param userName the user name of this amf audit event
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this amf audit event.
	 *
	 * @return the create date of this amf audit event
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this amf audit event.
	 *
	 * @param createDate the create date of this amf audit event
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this amf audit event.
	 *
	 * @return the modified date of this amf audit event
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this amf audit event.
	 *
	 * @param modifiedDate the modified date of this amf audit event
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the event type of this amf audit event.
	 *
	 * @return the event type of this amf audit event
	 */
	@AutoEscape
	public String getEventType();

	/**
	 * Sets the event type of this amf audit event.
	 *
	 * @param eventType the event type of this amf audit event
	 */
	public void setEventType(String eventType);

	/**
	 * Returns the ip address of this amf audit event.
	 *
	 * @return the ip address of this amf audit event
	 */
	@AutoEscape
	public String getIpAddress();

	/**
	 * Sets the ip address of this amf audit event.
	 *
	 * @param ipAddress the ip address of this amf audit event
	 */
	public void setIpAddress(String ipAddress);

	/**
	 * Returns the group ID of this amf audit event.
	 *
	 * @return the group ID of this amf audit event
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this amf audit event.
	 *
	 * @param groupId the group ID of this amf audit event
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this amf audit event.
	 *
	 * @return the company ID of this amf audit event
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this amf audit event.
	 *
	 * @param companyId the company ID of this amf audit event
	 */
	@Override
	public void setCompanyId(long companyId);

}